[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rate_limiter = "BY1CwE5H6c2WwG2VXQJatWVecNCBBcFQgNZtZaYx1cXZ"

[programs.testnet]
rate_limiter = "BY1CwE5H6c2WwG2VXQJatWVecNCBBcFQgNZtZaYx1cXZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "/home/ancestor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
